name: CI-Pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Configure Sonar-Analysis
        run: |
          . ./.github/configureSonarAnalysis.sh
      - name: Build and check library
        uses: christopherfrieler/gradle-wrapper-action@0.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: |
            check sonarqube assemble sourcesJar javadocJar
          artifacts: |
            jars build/libs/pbqp-*.jar
